name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.
  - type: textarea
    id: reproduction
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        When I run shell-guard in [X] state, it [Y] instead of [Z].
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do we trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS version, Git version, Shell type.
      placeholder: TUXEDO OS, Git 2.45.0, zsh
